name: ema_educacion_medica_avanzada
description: "ema - Educación Médica Avanzada"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  country_flags: ^3.3.0
  dio: ^5.8.0+1
  file_picker: ^9.0.0
  fl_chart: ^0.70.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  # flutter_markdown: ^0.7.6+2
  flutter_pdfview: ^1.4.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  get: ^4.6.6
  google_fonts: ^6.2.1
  gpt_markdown: ^1.0.11
  graphic: ^2.5.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  mime: ^2.0.0
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.3

flutter:
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/icons/platform/
    - assets/icons/svgs/
    - assets/images/

  uses-material-design: true

flutter_launcher_icons:
  image_path_android: "assets/icons/platform/icon-710x599-android.png"
  image_path_ios: "assets/icons/platform/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/icons/platform/icon-background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icons/platform/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/icons/platform/icon-monochrome-432x432.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
